function seqs=configSeqs

str = 'D:\softdata\Matlab\VTB1.0_DataSets\VTB1.0_DataSequence\';
seqs = {
struct('name','basketball','path',[str,'basketball','\img\'],'startFrame',1,'endFrame',725,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','biker','path',[str,'biker','\img\'],'startFrame',1,'endFrame',142,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','bird1','path',[str,'bird1','\img\'],'startFrame',1,'endFrame',408,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','blurbody','path',[str,'blurbody','\img\'],'startFrame',1,'endFrame',334,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','blurcar2','path',[str,'blurcar2','\img\'],'startFrame',1,'endFrame',585,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','blurface','path',[str,'blurface','\img\'],'startFrame',1,'endFrame',493,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','blurowl','path',[str,'blurowl','\img\'],'startFrame',1,'endFrame',631,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','bolt','path',[str,'bolt','\img\'],'startFrame',1,'endFrame',350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','box','path',[str,'box','\img\'],'startFrame',1,'endFrame',1161,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','car1','path',[str,'car1','\img\'],'startFrame',1,'endFrame',1020,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','car4','path',[str,'car4','\img\'],'startFrame',1,'endFrame',659,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','cardark','path',[str,'cardark','\img\'],'startFrame',1,'endFrame',393,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','carscale','path',[str,'carScale','\img\'],'startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','clifbar','path',[str,'clifbar','\img\'],'startFrame',1,'endFrame',472,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','couple','path',[str,'couple','\img\'],'startFrame',1,'endFrame',140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','crowds','path',[str,'crowds','\img\'],'startFrame',1,'endFrame',347,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','david','path',[str,'david','\img\'],'startFrame',300,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','deer','path',[str,'deer','\img\'],'startFrame',1,'endFrame',71,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','diving','path',[str,'diving','\img\'],'startFrame',1,'endFrame',215,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','dragonbaby','path',[str,'dragonbaby','\img\'],'startFrame',1,'endFrame',113,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','dudek','path',[str,'dudek','\img\'],'startFrame',1,'endFrame',1145,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','football','path',[str,'football','\img\'],'startFrame',1,'endFrame',362,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','freeman4','path',[str,'freeman4','\img\'],'startFrame',1,'endFrame',283,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','girl','path',[str,'girl','\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','human3','path',[str,'human3','\img\'],'startFrame',1,'endFrame',1698,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','human4-2','path',[str,'human4-2','\img\'],'startFrame',1,'endFrame',667,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','human6','path',[str,'human6','\img\'],'startFrame',1,'endFrame',792,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','human9','path',[str,'human9','\img\'],'startFrame',1,'endFrame',305,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','ironman','path',[str,'ironman','\img\'],'startFrame',1,'endFrame',166,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','jump','path',[str,'jump','\img\'],'startFrame',1,'endFrame',122,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','jumping','path',[str,'jumping','\img\'],'startFrame',1,'endFrame',313,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','liquor','path',[str,'liquor','\img\'],'startFrame',1,'endFrame',1741,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','matrix','path',[str,'matrix','\img\'],'startFrame',1,'endFrame',100,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','motorrolling','path',[str,'motorrolling','\img\'],'startFrame',1,'endFrame',164,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','panda','path',[str,'panda','\img\'],'startFrame',1,'endFrame',1000,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','redteam','path',[str,'redteam','\img\'],'startFrame',1,'endFrame',1918,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','shaking','path',[str,'shaking','\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','singer2','path',[str,'singer2','\img\'],'startFrame',1,'endFrame',366,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','skating1','path',[str,'skating1','\img\'],'startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','skating2-1','path',[str,'skating2-1','\img\'],'startFrame',1,'endFrame',473,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','skating2-2','path',[str,'skating2-2','\img\'],'startFrame',1,'endFrame',473,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','skiing','path',[str,'skiing','\img\'],'startFrame',1,'endFrame',81,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','soccer','path',[str,'soccer','\img\'],'startFrame',1,'endFrame',392,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','surfer','path',[str,'surfer','\img\'],'startFrame',1,'endFrame',376,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','sylvester','path',[str,'sylvester','\img\'],'startFrame',1,'endFrame',1345,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','tiger2','path',[str,'tiger2','\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','trellis','path',[str,'trellis','\img\'],'startFrame',1,'endFrame',569,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','walking','path',[str,'walking','\img\'],'startFrame',1,'endFrame',412,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','walking2','path',[str,'walking2','\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
struct('name','woman','path',[str,'woman','\img\'],'startFrame',1,'endFrame',597,'nz',4,'ext','jpg','init_rect', [0,0,0,0])
};

% function seqs=configSeqs
% 
% str = 'D:\softdata\Matlab\tracker_release2\data\Benchmark\';
% 
% 
% seqVTD={struct('name','soccer','path',[str,'soccer','\img\'],'startFrame',1,'endFrame',392,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','matrix','path',[str,'matrix','\img\'],'startFrame',1,'endFrame',100,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','ironman','path',[str,'ironman','\img\'],'startFrame',1,'endFrame',166,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','deer','path',[str,'deer','\img\'],'startFrame',1,'endFrame',71,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','skating1','path',[str,'skating1','\img\'],'startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','shaking','path',[str,'shaking','\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','singer1','path',[str,'singer1','\img\'],'startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','singer2','path',[str,'singer2','\img\'],'startFrame',1,'endFrame',366,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
% 
% seqIVT={struct('name','carDark','path',[str,'carDark','\img\'],'startFrame',1,'endFrame',393,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','car4','path',[str,'car4','\img\'],'startFrame',1,'endFrame',659,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','david','path',[str,'david','\img\'],'startFrame',300,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','david2','path',[str,'david2','\img\'],'startFrame',1,'endFrame',537,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...    
%     struct('name','sylvester','path',[str,'sylvester','\img\'],'startFrame',1,'endFrame',1345,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','trellis','path',[str,'trellis','\img\'],'startFrame',1,'endFrame',569,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','fish','path',[str,'fish','\img\'],'startFrame',1,'endFrame',476,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','mhyang','path',[str,'mhyang','\img\'],'startFrame',1,'endFrame',1490,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
% 
% seqOther={struct('name','coke','path',[str,'coke','\img\'],'startFrame',1,'endFrame',291,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','bolt','path',[str,'bolt','\img\'],'startFrame',1,'endFrame',350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','boy','path',[str,'boy','\img\'],'startFrame',1,'endFrame',602,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','dudek','path',[str,'dudek','\img\'],'startFrame',1,'endFrame',1145,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','crossing','path',[str,'crossing','\img\'],'startFrame',1,'endFrame',120,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','couple','path',[str,'couple','\img\'],'startFrame',1,'endFrame',140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','football1','path',[str,'football1','\img\'],'startFrame',1,'endFrame',74,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','jogging-1','path',[str,'jogging-1','\img\'],'startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','jogging-2','path',[str,'jogging-2','\img\'],'startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','doll','path',[str,'doll','\img\'],'startFrame',1,'endFrame',3872,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','girl','path',[str,'girl','\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','walking2','path',[str,'walking2','\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','walking','path',[str,'walking','\img\'],'startFrame',1,'endFrame',412,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','fleetface','path',[str,'fleetface','\img\'],'startFrame',1,'endFrame',707,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','freeman1','path',[str,'freeman1','\img\'],'startFrame',1,'endFrame',326,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','freeman3','path',[str,'freeman3','\img\'],'startFrame',1,'endFrame',460,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','freeman4','path',[str,'freeman4','\img\'],'startFrame',1,'endFrame',283,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','david3','path',[str,'david3','\img\'],'startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','jumping','path',[str,'jumping','\img\'],'startFrame',1,'endFrame',313,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','carScale','path',[str,'carScale','\img\'],'startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','skiing','path',[str,'skiing','\img\'],'startFrame',1,'endFrame',81,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','dog1','path',[str,'dog1','\img\'],'startFrame',1,'endFrame',1350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','suv','path',[str,'suv','\img\'],'startFrame',1,'endFrame',945,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','motorRolling','path',[str,'motorRolling','\img\'],'startFrame',1,'endFrame',164,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','mountainBike','path',[str,'mountainBike','\img\'],'startFrame',1,'endFrame',228,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),... 
%     struct('name','lemming','path',[str,'lemming','\img\'],'startFrame',1,'endFrame',1336,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','liquor','path',[str,'liquor','\img\'],'startFrame',1,'endFrame',1741,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','woman','path',[str,'woman','\img\'],'startFrame',1,'endFrame',597,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','faceocc1','path',[str,'faceocc1','\img\'],'startFrame',1,'endFrame',892,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','faceocc2','path',[str,'faceocc2','\img\'],'startFrame',1,'endFrame',812,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','basketball','path',[str,'basketball','\img\'],'startFrame',1,'endFrame',725,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','football','path',[str,'football','\img\'],'startFrame',1,'endFrame',362,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','subway','path',[str,'subway','\img\'],'startFrame',1,'endFrame',175,'nz',4,'ext','jpg','init_rect', [0 0 0 0]),...    
%     struct('name','tiger1','path',[str,'tiger1','\img\'],'startFrame',1,'endFrame',354,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','tiger2','path',[str,'tiger2','\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
% 
% seqs=[seqIVT,seqVTD,seqOther];
% 

